### ISSUE TITLE
4 May 2020

### ISSUE THREAD

**Issue by GordonBeeming** [South-Africa-Durban-UG/Meetups#1]
This is a how's are things going kind of a chat to touch base and then chat about what we could do as presentations and sessions going forward from there with everyone.

Please feel free to comment with topic ideas and up vote using reactions if you agree with a topic 😁

To Join us virtually RSVP on meetup https://www.meetup.com/Azure-Transformation-Labs/events/270357007/

**Comment by nielsberglund** [comment]
So for Monday, maybe chat about how lockdown is going, what people do to be effective, etc.

**Comment by pivendren** [comment]
I have been toying around with some software on my journey to becoming a VC ninja. I can chat quickly about Snap Camera and RTX Voice.

**Comment by GordonBeeming** [comment]
> I have been toying around with some software on my journey to becoming a VC ninja. I can chat quickly about Snap Camera and RTX Voice.

Snap Camera is awesome, I've been playing around with that a lot in work teams calls 😁

![image](https://user-images.githubusercontent.com/5680199/80625977-3042fc80-8a4e-11ea-84d9-5bc7471d8769.png)

![image](https://user-images.githubusercontent.com/5680199/80625991-32a55680-8a4e-11ea-9343-3d9d15de4925.png)

**Comment by RonaldMariah** [comment]
One of the topics we could speak about is taking exams from home and the process/experience of  taking an exam online compared to the in-person test experience. I've done two exams so far since being in Lockdown (DP-300 Beta and DP-201).

**Comment by GordonBeeming** [comment]
Virtual events... has anyone done any in lockdown, how were they? Did everyone get the message about Build being a free virtual event this year

**Comment by GordonBeeming** [comment]
Recording for the session is on YouTube

[![2020-05-05_21-12-14](https://user-images.githubusercontent.com/5680199/81112225-9e8c3100-8f1e-11ea-894a-bea8f9a10f15.jpg)](https://www.youtube.com/watch?v=IxRqC5XpQSc)
